services:
  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    volumes:
      - letsencrypt:/letsencrypt

  backend:
    labels:
      - traefik.enable=true
      - traefik.docker.network=desigram
      - traefik.http.routers.backend.rule=Host(`api.desigram.com`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=le
      - traefik.http.services.backend.loadbalancer.server.port=8080

  frontend:
    build:
      context: ../frontend
      dockerfile: ../enviropment/nextjs/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://api.desigram.com
    environment:
      NEXT_PUBLIC_API_URL: https://api.desigram.com
    labels:
      - traefik.enable=true
      - traefik.docker.network=desigram
      - traefik.http.routers.frontend.rule=Host(`desigram.com`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.services.frontend.loadbalancer.server.port=3000

volumes:
  letsencrypt:
