services:
  traefik:
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --log.level=WARN

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    volumes:
      - letsencrypt:/letsencrypt

  core:
    labels:
      - traefik.http.routers.core.tls.certresolver=le
      - traefik.http.routers.core.middlewares=hsts@file,secure-headers@file,api-headers@file,core-ratelimit

  auth:
    labels:
      - traefik.http.routers.auth.tls.certresolver=le
      - traefik.http.routers.auth.middlewares=hsts@file,secure-headers@file,api-headers@file,api-cors@file,auth-ratelimit

  frontend:
    labels:
      - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.routers.frontend.middlewares=hsts@file,secure-headers@file,app-csp@file

volumes:
  letsencrypt:
